repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: forbid-binary
